image: php:8.2-fpm

pipelines:
  default:
    - parallel:
      - step:
         services:
           - mysql
         name: 'Build and Test'
         script:
           # Build the project
           - apt -qy update
           - apt -qy install curl git zip unzip libzip-dev default-mysql-client
           - docker-php-ext-install pdo_mysql ctype bcmath zip
           - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
           - apt -qy install npm
           - composer install --no-interaction
           - npm install
           - php artisan key:generate
           - php artisan migrate --no-interaction
           - php artisan db:seed
           - npm run prod
           # Start server
           - php artisan serve &
           - sleep 5
           # Run PHP Unit Tests
           - ./vendor/bin/phpunit

     
definitions:
 services:
   mysql:
     image: mysql:8.0
     environment:
       MYSQL_DATABASE: 'laravel'
       MYSQL_ROOT_PASSWORD: 'l@r@vel'
       